name: cbir-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip

  # Image processing & computer vision
  - numpy
  - matplotlib

  # pip-only packages
  - pip:
    - opencv-python==4.10.0.84
    - tensorflow==2.13.0
    - keras==2.13.1
